### ISSUE TITLE
[CRASH] Certain boards crash the game, because the FEN validator misses some edge cases

### ISSUE THREAD

**Issue by Ganpan14O** [andrew0030/Table-Top-Craft#16] opened 2022-12-16 09:14 UTC
**To Reproduce**
Steps to reproduce the crash:
1. Create or find an FEN without a king 
2. Load it into the chess board

**Crash log**
https://pastebin.com/kLTUtJYR

**Versions**
table_top_craft-1.18.2-2.1.1

**Additional context**
This seems potentially intentional by the crash log, and if it is intentional, I would like to see an alternative to crashing the game, such as not accepting kingless FENs or resetting the board if there is no king, to be used.

**Edit**
1. This was in fact not from there being no king but rather from the specific FEN 1NQN3q/NQ1QN3/Q1k1Q3/NQ1QN3/1NQN4/5qn1/5n2/q6K w - - 0 1

**Comment by andrew0030** [comment] 2022-12-16 14:07
I mean this is happening because there is an issue with the number of Kings yes.
That said, I can not reproduce this. Like I have built in a validation into the FEN loader and if you give it an invalid one it just loads the standard Board. I have tested multiple FEN's but they all get detected as invalid.

Did you manually alter the FEN in the blocks NBT?
If not can you send me the FEN you tried to load that caused the crash?

**Comment by Ganpan14O** [comment] 2022-12-16 20:30
Now that I think of it, I the board actually had a king but still did that, the FEN was 1NQN3q/NQ1QN3/Q1k1Q3/NQ1QN3/1NQN4/5qn1/5n2/q6K w - - 0 1

**Comment by andrew0030** [comment] 2022-12-16 20:47
what kind of FEN is that O.o

**Comment by Ganpan14O** [comment] 2022-12-17 01:26
> what kind of FEN is that O.o

I was messing around and changing my friend's boards to joke situations.

**Comment by andrew0030** [comment] 2022-12-17 01:27
I see
Well I have been messing around with it, and I will say this is surprisingly hard to deal with

**Comment by andrew0030** [comment] 2022-12-17 01:50
Ok so update, I think I have figured out a way to prevent this.
I will do more testing tomorrow, and if Im happy with it I will release a fix for all versions (1.18.2, 1.19 and 1.19.3) both forge and fabric.
That said if you see this before I released the fix, feel free to give me more joke lineups, so I can test more potential breaks.

**Comment by andrew0030** [comment] 2022-12-21 01:38
This has been fixed in all latest versions.

**Closed by andrew0030** 2022-12-21 01:38 UTC
Labels: bug
